### ISSUE TITLE
java.lang.IncompatibleClassChangeError caused by asm

### ISSUE THREAD

**Issue by obecker** [obecker/gradle-degraph#1]
Using the degraph plugin in a project with this simple configuration

    plugins {
        id 'org.openrepose.gradle.plugins.jaxb' version '2.2.3'
        id 'de.obqo.gradle.degraph' version '0.1.4.0'
    }

produces the following exception:

    java.lang.IncompatibleClassChangeError: class de.schauderhaft.degraph.analysis.asm.GraphBuildingClassVisitor has interface org.objectweb.asm.ClassVisitor as super class
        at de.schauderhaft.degraph.analysis.asm.Analyzer$.readStream$1(Analyzer.scala:17)
        at de.schauderhaft.degraph.analysis.asm.Analyzer$.de$schauderhaft$degraph$analysis$asm$Analyzer$$analyze$1(Analyzer.scala:33)
        at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1$$anonfun$apply$1.apply(Analyzer.scala:51)
        at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1$$anonfun$apply$1.apply(Analyzer.scala:50)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
        at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1.apply(Analyzer.scala:50)
        at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1.apply(Analyzer.scala:47)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at de.schauderhaft.degraph.analysis.asm.Analyzer$.analyze(Analyzer.scala:47)
        at de.schauderhaft.degraph.configuration.Configuration.createGraph(Configuration.scala:26)
        at de.schauderhaft.degraph.check.Check$$anon$1.apply(Check.scala:56)
        at de.schauderhaft.degraph.check.Check$$anon$1.apply(Check.scala:53)
        at de.obqo.gradle.degraph.DegraphTask.runConstraintCheck(DegraphTask.java:87)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more

**Comment by obecker** [comment]
This happens because both plugins `org.openrepose.gradle.plugins.jaxb` and `de.obqo.gradle.degraph` pull the `asm` library into the build classpath, however in different incompatible versions.

The solution to prevent these kinds of errors is to use the gradle worker API that enables a dedicated plugin classpath that will not interfere with other plugins of the same build.

**Comment by obecker** [comment]
Fixed in v0.1.4.1
